CREATE TABLE IF NOT EXISTS player_game_stats (
    game_id TEXT NOT NULL,
    player_id TEXT NOT NULL,
    season_type TEXT NOT NULL,
    season INTEGER NOT NULL,
    week INTEGER NOT NULL,
    pass_att INTEGER,
    pass_sack INTEGER,
    pass_att_ez INTEGER,
    pass_att_rz INTEGER,
    pass_td_rz INTEGER,
    pass_cmp INTEGER,
    pass_yds INTEGER,
    pass_td INTEGER,
    pass_int INTEGER,
    pass_air_yds_comp INTEGER,
    pass_air_yds_tot INTEGER,
    pass_ep DOUBLE PRECISION,
    pass_epa DOUBLE PRECISION,
    rec_tgt INTEGER,
    rec_tgt_ez INTEGER,
    rec_tgt_rz INTEGER,
    rec_rz INTEGER,
    rec_td_rz INTEGER,
    rec INTEGER,
    rec_yds INTEGER,
    rec_td INTEGER,
    rec_air_yds_comp INTEGER,
    rec_air_yds_tot INTEGER,
    rec_ep DOUBLE PRECISION,
    rec_epa DOUBLE PRECISION,
    rush_gl_att INTEGER,
    rush_rz_att INTEGER,
    rush_att INTEGER,
    rush_yds INTEGER,
    rush_td INTEGER,
    rush_successes INTEGER,
    rush_ep DOUBLE PRECISION,
    rush_epa DOUBLE PRECISION,
    off_snp INTEGER,
    team_plays INTEGER,
    team_pass_att INTEGER,
    team_pass_cmp INTEGER,
    team_pass_yd INTEGER,
    team_pass_td INTEGER,
    team_air_yds_comp INTEGER,
    team_air_yds_tot INTEGER,
    kickoff BIGINT,
    PRIMARY KEY (game_id, player_id)
);